
#define MUTEX_LOCK_WAIT_TIME		50000

#ifndef _MUTEX_H_
#define _MUTEX_H_

enum  MUTEX_PRIO
{
	UPPER_PRIO_READ_WRITE_SETDATA      =   4,
	UPPER_PRIO_READ_WRITE_CANCOMM_DATA =   5,
	UPPER_PRIO_READ_WRITE_I2CCOMM_DATA =   6,
	UPPER_PRIO_READ_WRITE_MEASURE_DATA =   7,
	UPPER_PRIO_WRITE_UART_DATA         =   8,
	UPPER_PRIO_READ_WRITE_E2PROM_DATA  =   9,
	UPPER_PRIO_READ_WRITE_RELAY_DATA   =   10,  
	UPPER_PRIO_READ_WRITE_NETBUF_DATA  =   11,
	UPPER_PRIO_READ_WRITE_EV_DATA  =   12,
	UPPER_PRIO_NET_R_W_BUF  =   13,
	UPPER_PRIO_OPERATE_SPI_FLASH = 14,
	UPPER_PRIO_NET_W_BUF  =   15,
	UPPER_PRIO_ALM_INFO  =   16,
	UPPER_PRIO_FLASH_INFO  =   17,

	UPPER_PRIO_WRITE_CAN3  =   18,
	UPPER_PRIO_CAN_RING_A  =   19, 
	UPPER_PRIO_CAN_RING_B  =   20, 
};

enum  MUTEX_RTN
{
	ERR_MUTEX_TIMEOUT,
	ERR_MUTEX_OK,
};

HANDLE MutexCreate(UCHAR prio);
UCHAR MutexLock(HANDLE hm);
void MutexUnlock(HANDLE hm);
UCHAR InitMutex(void);

#endif















