/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : extWdog1.h
**     Project     : S32K1xxAppDev_Safety_Demo
**     Processor   : S32K144_100
**     Component   : ewm
**     Version     : Component SDK_S32K14x_12, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_12
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-05-08, 00:45, # CodeGen: 0
**     Contents    :
**         EWM_DRV_Init                   - status_t EWM_DRV_Init(uint32_t instance,const ewm_init_config_t * config);
**         EWM_DRV_GetDefaultConfig       - void EWM_DRV_GetDefaultConfig(ewm_init_config_t * config);
**         EWM_DRV_Refresh                - void EWM_DRV_Refresh(uint32_t instance);
**         EWM_DRV_GetInputPinAssertLogic - ewm_in_assert_logic_t EWM_DRV_GetInputPinAssertLogic(uint32_t instance);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file extWdog1.h
** @version 01.00
*/
/*!
**  @addtogroup extWdog1_module extWdog1 module documentation
**  @{
*/
#ifndef extWdog1_H
#define extWdog1_H
/* MODULE extWdog1. */
/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "ewm_driver.h"

/*! @brief Device instance number */
#define EXTWDOG1 0UL


/*! @brief Declarations of configuration structures */
extern const ewm_init_config_t extWdog1_Config0;

#endif
/* ifndef extWdog1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
