/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : memProtect1.h
**     Project     : S32K1xxAppDev_Safety_Demo
**     Processor   : S32K144_100
**     Component   : mpu
**     Version     : Component SDK_S32K14x_12, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_12
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-05-08, 00:45, # CodeGen: 0
**     Contents    :
**         MPU_DRV_Init                     - status_t MPU_DRV_Init(uint32_t instance, uint8_t regionCnt, const...
**         MPU_DRV_Deinit                   - void MPU_DRV_Deinit(uint32_t instance);
**         MPU_DRV_SetRegionAddr            - void MPU_DRV_SetRegionAddr(uint32_t instance, uint8_t regionNum, uint32_t...
**         MPU_DRV_SetRegionConfig          - status_t MPU_DRV_SetRegionConfig(uint32_t instance, uint8_t regionNum, const...
**         MPU_DRV_SetMasterAccessRights    - status_t MPU_DRV_SetMasterAccessRights(uint32_t instance, uint8_t regionNum,...
**         MPU_DRV_GetDetailErrorAccessInfo - bool MPU_DRV_GetDetailErrorAccessInfo(uint32_t instance, uint8_t...
**         MPU_DRV_GetDefaultRegionConfig   - mpu_user_config_t MPU_DRV_GetDefaultRegionConfig(mpu_master_access_right_t *...
**         MPU_DRV_EnableRegion             - void MPU_DRV_EnableRegion(uint32_t instance, uint8_t regionNum, bool enable);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file memProtect1.h
** @version 01.00
*/
/*!
**  @addtogroup memProtect1_module memProtect1 module documentation
**  @{
*/
#ifndef memProtect1_H
#define memProtect1_H

/* MODULE memProtect1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define MEMPROTECT1 (0U)

/*! @brief Number of user configuration */
#define MPU_NUM_OF_USER_CFG (1U)

/*! @brief Number of region in user configuration */
#define MPU_NUM_OF_REGION_CFG0 (8U)

/*! @brief User configuration */
extern mpu_user_config_t memProtect1_UserConfig0[MPU_NUM_OF_REGION_CFG0];

/*! @brief Master access rights */
extern const mpu_master_access_right_t memProtect1_AccessRightConfig0[FEATURE_MPU_MASTER_COUNT];
extern const mpu_master_access_right_t memProtect1_AccessRightConfig1[FEATURE_MPU_MASTER_COUNT];
extern const mpu_master_access_right_t memProtect1_AccessRightConfig2[FEATURE_MPU_MASTER_COUNT];

#endif
/* ifndef memProtect1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
