/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : memProtect1.c
**     Project     : S32K1xxAppDev_Safety_Demo
**     Processor   : S32K144_100
**     Component   : mpu
**     Version     : Component SDK_S32K14x_12, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_12
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-05-08, 00:45, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file memProtect1.c
** @version 01.00
*/
/*!
**  @addtogroup memProtect1_module memProtect1 module documentation
**  @{
*/

/* MODULE memProtect1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source file that user initialize
 * to use this module.
 */

#include "memProtect1.h"

/*! Master access rights configuration 0 */
const mpu_master_access_right_t memProtect1_AccessRightConfig0[] =
{
    /*! CORE */
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,                   /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_NONE,                /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    },
    /*! DEBUGGER */
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,               /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_RWX,                 /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    },
    /*! DMA */
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,                    /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_NONE,                /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    }
};
/*! Master access rights configuration 1 */
const mpu_master_access_right_t memProtect1_AccessRightConfig1[] =
{
    /*! CORE */
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,                   /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_RWX,                 /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    },
    /*! DEBUGGER */
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,               /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_RWX,                 /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    },
    /*! DMA */
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,                    /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_RWX,                 /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    }
};
/*! Master access rights configuration 2 */
const mpu_master_access_right_t memProtect1_AccessRightConfig2[] =
{
    /*! CORE */
    {
        .masterNum = FEATURE_MPU_MASTER_CORE,                   /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_RX,                  /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    },
    /*! DEBUGGER */
    {
        .masterNum = FEATURE_MPU_MASTER_DEBUGGER,               /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_RWX,                 /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    },
    /*! DMA */
    {
        .masterNum = FEATURE_MPU_MASTER_DMA,                    /*!< Master number */
        .accessRight = MPU_SUPERVISOR_USER_RX,                  /*!< Access right */
        .processIdentifierEnable = false                        /*!< Process identifier enable */
    }
};

/*! User configuration 0 */
mpu_user_config_t memProtect1_UserConfig0[] =
{
    /*! Region number 0 */
    {
        .startAddr         = 0x00000000U,                       /*!< Memory region start address */
        .endAddr           = 0xFFFFFFFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig0,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    },
    /*! Region number 1 */
    {
        .startAddr         = 0x00000000U,                       /*!< Memory region start address */
        .endAddr           = 0x00003FFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig2,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    },
    /*! Region number 2 */
    {
        .startAddr         = 0x00004000U,                       /*!< Memory region start address */
        .endAddr           = 0x0007FFFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig1,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    },
    /*! Region number 3 */
    {
        .startAddr         = 0x10000000U,                       /*!< Memory region start address */
        .endAddr           = 0x14001FFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig1,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    },
    /*! Region number 4 */
    {
        .startAddr         = 0x1FFF8000U,                       /*!< Memory region start address */
        .endAddr           = 0x1FFFFFFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig1,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    },
    /*! Region number 5 */
    {
        .startAddr         = 0x20000000U,                       /*!< Memory region start address */
        .endAddr           = 0x20006FFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig1,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    },
    /*! Region number 6 */
    {
        .startAddr         = 0x40000000U,                       /*!< Memory region start address */
        .endAddr           = 0x6FFFFFFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig1,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    },
    /*! Region number 7 */
    {
        .startAddr         = 0xE0000000U,                       /*!< Memory region start address */
        .endAddr           = 0xFFFFFFFFU,                       /*!< Memory region end address */
        .masterAccRight    = memProtect1_AccessRightConfig1,    /*!< Master access right */
        .processIdentifier = 0x00U,                             /*!< Process identifier */
        .processIdMask     = 0x00U                              /*!< Process identifier mask */
    }
};
/* END memProtect1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
