/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eqadc1.c
**     Project     : FS65_Cobra_Example
**     Processor   : MPC5777C_516
**     Component   : eqadc
**     Version     : Component S32_SDK, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-01-02, 17:42, # CodeGen: 17
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eqadc1.c
** @version 01.00
*/
/*!
**  @addtogroup eqadc1_module eqadc1 module documentation
**  @{
*/

/* MODULE eqadc1. */

#include "eqadc1.h"



/*! @brief ***** Configuration structures for config 0 ***** */
const eqadc_config_t eqadc1_config0 = {
    .dbgReqMaskEn             = false,
    .digitalFilterLen         = 0u,
    .timebasePrescale         = EQADC_TIMEBASE_PRESCALE_DISABLED,
    .adcConfigArray           = eqadc1_adcConfigArray0,
    .numAdcConfigs            = 1u,
    .cfifoConfigArray         = eqadc1_cfifoConfigArray0,
    .numCfifoConfigs          = 1u,
    .resultDmaConfigArray     = NULL,
    .numResultDmaConfigs      = 0u,
    .alternateConfigArray     = NULL,
    .numAlternateConfigs      = 0u,
    .extAlternateConfigArray  = NULL,
    .numExtAlternateConfigs   = 0u,
    .chanPullConfigArray      = NULL,
    .numChanPullConfigs       = 0u,
    .stacBusClientConfigArray = NULL,
    .numStacBusClientConfigs  = 0u,
};

/*! @brief ADC config array 0 */
eqadc_adc_config_t eqadc1_adcConfigArray0[1u] = {
/* adcIdx, extMuxEn, timebaseSel,                clkPrescale,               clkOddPrescaleEn, clkDutySel,   adcGain,   adcOffset,   immediateConvCmdEn  */
{  0u,     false,    EQADC_TIMEBASE_SEL_INTERNAL, EQADC_PRESCALE_NOT_USED,    false,             false,        16384u,         0u,         false },
};

/*! @brief CFIFO config array 0 */
eqadc_cfifo_config_t eqadc1_cfifoConfigArray0[1u] = {
{ /*cfifoIdx*/ 0u, /*opMode*/ EQADC_CFIFO_MODE_SW_TRIG_SINGLE, /*fillReqSel*/ EQADC_REQ_TYPE_SEL_INT, /*dmaVirtualChan*/ 0u, /*sourcePtr*/ NULL, /*sourceLength*/ 2, /*callback*/ NULL, /*callbackParam*/ NULL, \
                   /*trigSel*/ 0, /*tbgClksel*/ EQADC_TBG_CLKSEL_DISABLED, /*tbgTriggerPeriod*/ 0, /*entryNumExtensionEn*/ false, /*advanceTrigMode*/ EQADC_ATRIG_MODE_DISABLED, /*advanceTrigSel*/ 0 },
};

/*! @brief Command buffers for CFIFO config 0 with DMA enabled  */


/*! @brief ***** Conversion Commands Array 0 ***** */
const eqadc_conv_cmd_t eqadc1_convCmdArray0[1u] = {
/* eoq, pause, repeatStart, cBufferNum, calibEn, msgTag,                    samplingTime,                 timeStampReq, channelNum, signEn, altConfigSel,                   flushCompanion  */
{ false, false, false,       0u,        false,   EQADC_MESSAGE_TAG_RFIFO0,  EQADC_SAMPLING_TIME_2_CYCLES, false,        4u,         false,  EQADC_ALT_CONFIG_SEL_DISABLED,  false },
};


/*! eqadc1 configuration structures */
/* END eqadc1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

