/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eqadc1.h
**     Project     : FS65_Cobra_Example
**     Processor   : MPC5777C_516
**     Component   : eqadc
**     Version     : Component S32_SDK, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-13, 10:32, # CodeGen: 13
**     Contents    :
**         EQADC_DRV_GetDefaultConfig             - void EQADC_DRV_GetDefaultConfig(eqadc_config_t *const config);
**         EQADC_DRV_Init                         - void EQADC_DRV_Init(const uint32_t instance,const eqadc_config_t *const config);
**         EQADC_DRV_Reset                        - void EQADC_DRV_Reset(const uint32_t instance);
**         EQADC_DRV_SetSingleScanEnBit           - void EQADC_DRV_SetSingleScanEnBit(const uint32_t instance,const uint32_t...
**         EQADC_DRV_EnableImmediateConvCmd       - void EQADC_DRV_EnableImmediateConvCmd(const uint32_t instance,const uint32_t...
**         EQADC_DRV_DisableImmediateConvCmd      - void EQADC_DRV_DisableImmediateConvCmd(const uint32_t instance,const uint32_t...
**         EQADC_DRV_GetFifoStatus                - uint8_t EQADC_DRV_GetFifoStatus(const uint32_t instance,const uint32_t...
**         EQADC_DRV_ClearFifoStatus              - void EQADC_DRV_ClearFifoStatus(const uint32_t instance,const uint32_t...
**         EQADC_DRV_EnableIntReq                 - void EQADC_DRV_EnableIntReq(const uint32_t instance,const uint32_t...
**         EQADC_DRV_DisableIntReq                - void EQADC_DRV_DisableIntReq(const uint32_t instance,const uint32_t...
**         EQADC_DRV_EnableDmaReq                 - void EQADC_DRV_EnableDmaReq(const uint32_t instance,const uint32_t...
**         EQADC_DRV_DisableDmaReq                - void EQADC_DRV_DisableDmaReq(const uint32_t instance,const uint32_t...
**         EQADC_DRV_PushCfifoConvCmd             - void EQADC_DRV_PushCfifoConvCmd(const uint32_t instance,const uint32_t...
**         EQADC_DRV_WriteMemConvCmd              - void EQADC_DRV_WriteMemConvCmd(const eqadc_conv_cmd_t *const...
**         EQADC_DRV_PushCfifoConfigCmd           - void EQADC_DRV_PushCfifoConfigCmd(const uint32_t instance,const uint32_t...
**         EQADC_DRV_WriteMemConfigCmd            - void EQADC_DRV_WriteMemConfigCmd(const eqadc_config_cmd_t *const...
**         EQADC_DRV_PopRfifoData                 - uint16_t EQADC_DRV_PopRfifoData(const uint32_t instance,const uint32_t...
**         EQADC_DRV_GetCfifoEntry                - uint32_t EQADC_DRV_GetCfifoEntry(const uint32_t instance,const uint32_t...
**         EQADC_DRV_GetRfifoEntry                - uint16_t EQADC_DRV_GetRfifoEntry(const uint32_t instance,const uint32_t...
**         EQADC_DRV_GetTransferCount             - uint16_t EQADC_DRV_GetTransferCount(const uint32_t instance,const uint32_t...
**         EQADC_DRV_SetTransferCount             - void EQADC_DRV_SetTransferCount(const uint32_t instance,const uint32_t...
**         EQADC_DRV_GetCfifoStatusCurrent        - eqadc_cfifo_status_t EQADC_DRV_GetCfifoStatusCurrent(const uint32_t...
**         EQADC_DRV_GetCfifoStatusSnapshot       - eqadc_cfifo_status_t EQADC_DRV_GetCfifoStatusSnapshot(const uint32_t...
**         EQADC_DRV_GetCfifoLastCmdSource        - uint8_t EQADC_DRV_GetCfifoLastCmdSource(const uint32_t instance,const...
**         EQADC_DRV_GetCfifoTransferCountLastCmd - uint16_t EQADC_DRV_GetCfifoTransferCountLastCmd(const uint32_t instance,const...
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eqadc1.h
** @version 01.00
*/
/*!
**  @addtogroup eqadc1_module eqadc1 module documentation
**  @{
*/
#ifndef eqadc1_H
#define eqadc1_H

/* MODULE eqadc1. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, global macro not referenced
 * There are global macros defined to be used by the integrator and another one used as include guard.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * Variables are defined for usage by application code, from other source files.
 */

/* Include inherited modules */
#include "dmaController1.h"
#include "Cpu.h"
#include "eqadc_driver.h"


/*! @brief Device instance number */
#define INST_EQADC1 0U


/*! @brief ***** Configuration structures for config 0 ***** */
extern const eqadc_config_t eqadc1_config0;
extern eqadc_adc_config_t eqadc1_adcConfigArray0[1u];
extern eqadc_cfifo_config_t eqadc1_cfifoConfigArray0[1u];

/*! @brief Command buffers for CFIFO config 0 with DMA enabled  */

/*! @brief Function prototypes for callbacks used for DMA transfers for DMA config 0 */



/*! @brief ***** Conversion Commands Array 0 ***** */
extern const eqadc_conv_cmd_t eqadc1_convCmdArray0[1u];


#endif /* ifndef eqadc1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
