/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : esci1.h
**     Project     : FS65_Cobra_Example
**     Processor   : MPC5777C_516
**     Component   : esci
**     Version     : Component SDK_S32_PA_08, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-11, 12:38, # CodeGen: 10
**     Contents    :
**         ESCI_DRV_Init             - status_t ESCI_DRV_Init(const uint32_t instNum, const esci_user_config_t*...
**         ESCI_DRV_Deinit           - status_t ESCI_DRV_Deinit(const uint32_t instNum);
**         ESCI_DRV_GetDefaultConfig - status_t ESCI_DRV_GetDefaultConfig(esci_user_config_t* esciUserConfig);
**         ESCI_DRV_SetTxBuffer      - status_t ESCI_DRV_SetTxBuffer(const uint32_t instNum, const uint8_t* data,...
**         ESCI_DRV_SetRxBuffer      - status_t ESCI_DRV_SetRxBuffer(const uint32_t instNum, uint8_t* data, const...
**         ESCI_DRV_SetBaudRate      - status_t ESCI_DRV_SetBaudRate(const uint32_t instNum, uint32_t baudRate);
**         ESCI_DRV_GetBaudRate      - status_t ESCI_DRV_GetBaudRate(const uint32_t instNum, uint32_t *baudRate);
**         ESCI_DRV_Send             - status_t ESCI_DRV_Send(const uint32_t instNum, const esci_send_type_t...
**         ESCI_DRV_SendBlocking     - status_t ESCI_DRV_SendBlocking(const uint32_t instNum, const esci_send_type_t...
**         ESCI_DRV_GetSendStatus    - status_t ESCI_DRV_GetSendStatus(const uint32_t instNum, uint32_t *countRemain);
**         ESCI_DRV_AbortSend        - status_t ESCI_DRV_AbortSend(const uint32_t instNum);
**         ESCI_DRV_InstallCallback  - status_t ESCI_DRV_InstallCallback(const uint32_t instNum, const...
**         ESCI_DRV_Receive          - status_t ESCI_DRV_Receive(const uint32_t instNum, uint8_t* data, const...
**         ESCI_DRV_ReceiveBlocking  - status_t ESCI_DRV_ReceiveBlocking(const uint32_t instNum, uint8_t* data,...
**         ESCI_DRV_GetReceiveStatus - status_t ESCI_DRV_GetReceiveStatus(const uint32_t instNum, uint32_t...
**         ESCI_DRV_AbortReceive     - status_t ESCI_DRV_AbortReceive(const uint32_t instNum);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file esci1.h
** @version 01.00
*/
/*!
**  @addtogroup esci1_module esci1 module documentation
**  @{
*/

/* MODULE esci1
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The macros are defined to be used by application code.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.11, When an array with external linkage
 * is declared, its size should be explicitly specified.
 * The configuration structure needs a global member defined in application space.
 * The global member has to be an array with an application specific length, therefore,
 * it's size can not be determined at generation time.
 */

#ifndef esci1_H
#define esci1_H

/* Include inherited beans */
#include "clockMan1.h"
#include "dmaController1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define INST_ESCI1 (0U)

/*! @brief Driver state structure which holds driver runtime data */
extern esci_state_t esci1State;

/*! @brief Module configuration structures */
extern const esci_user_config_t esci1_InitConfig0;

#endif
/* ifndef esci1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/

