/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : esci1.c
**     Project     : FS65_Cobra_Example
**     Processor   : MPC5777C_516
**     Component   : esci
**     Version     : Component SDK_S32_PA_08, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_08
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-12-11, 13:45, # CodeGen: 11
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file esci1.c
** @version 01.00
*/
/*!
**  @addtogroup esci1_module esci1 module documentation
**  @{
*/

/* MODULE esci1
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files that user initialize
 * to use this module.
 */

#include "esci1.h"

/*Define state structure for current ESCI instance */
esci_state_t esci1State;


/* ESCI Configuration */
const esci_user_config_t esci1_InitConfig0 =
{
    .functionalMode = ESCI_MODE_SCI,
    .receiveInputMode = ESCI_RECV_MODE_DUAL_WIRE,
    .frameFormat =
    {
        .characterBits = ESCI_CHARACTER_BITS_8,
        .addressBits = false,
        .extraStopBit = false
    },
    .baudRate = 115200UL,
    .parityBits = false,
    .oddParity = false,
    .rxUserConfig =
    {
        .wakeupCondition = ESCI_WAKEUP_ADDRESS_MARK,
        .rxdInvertedPolarity = false,
        .dmaReception = false
    },
    .txUserConfig =
    {
        .dmaTransmission = false
    }
};

/* END esci1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/


