/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : erm1.c
**     Project     : S32K146OFBMU
**     Processor   : S32K146_100
**     Component   : erm
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-06-21, 14:21, # CodeGen: 152
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file erm1.c
** @version 01.00
*/         
/*!
**  @addtogroup erm1_module erm1 module documentation
**  @{
*/         

/* MODULE erm1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source file that user initialize
 * to use this module.
 */

#include "erm1.h"

/*********************************************
 * Interrupt configurations
 ********************************************/
/*! Interrupt configuration 0 */
const erm_interrupt_config_t erm1_Interrupt0 =
{
    .enableSingleCorrection = false,        /*!< Single correction interrupt disabled        */
    .enableNonCorrectable   = true          /*!< Non-correctable error interrupt enabled     */
};


/*********************************************
 * User configurations
 ********************************************/
/*! User configuration 0 */
const erm_user_config_t erm1_InitConfig0[] =
{
    /*! Channel 0U */
    {
        .channel      = 0U,
        .interruptCfg = &erm1_Interrupt0
    },

    /*! Channel 1U */
    {
        .channel      = 1U,
        .interruptCfg = &erm1_Interrupt0
    }
};


/* END erm1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
