/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : flexio_spi1.c
**     Project     : S32K146OFBMU
**     Processor   : S32K146_100
**     Component   : flexio_spi
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-06-21, 14:21, # CodeGen: 152
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file flexio_spi1.c
** @version 01.00
*/         
/*!
**  @addtogroup flexio_spi1_module flexio_spi1 module documentation
**  @{
*/         

/* MODULE flexio_spi1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 */

#include "flexio_spi1.h"


const flexio_spi_master_user_config_t flexio_spi1_MasterConfig0 = {
  .driverType = FLEXIO_DRIVER_TYPE_INTERRUPTS,
  .clockPolarity = 0U,
  .clockPhase = 0U,
  .baudRate = 2000000U,
  .bitOrder = FLEXIO_SPI_TRANSFER_MSB_FIRST,
  .transferSize = FLEXIO_SPI_TRANSFER_1BYTE,
  .mosiPin = 0U,
  .misoPin = 1U,
  .sckPin = 2U,
  .ssPin = 3U,
  .callback = NULL,
  .callbackParam = NULL,
  .txDMAChannel = 255U,
  .rxDMAChannel = 255U,
};


/* END flexio_spi1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
