/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : spi3_pal.c
**     Project     : S32K146OFBMU
**     Processor   : S32K146_100
**     Component   : spi_pal
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2022-06-21, 14:21, # CodeGen: 152
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file spi3_pal.c
** @version 01.00
*/         
/*!
**  @addtogroup spi3_pal_module spi3_pal module documentation
**  @{
*/         
#include "spi3_pal.h"

/*
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * This structure is defined for usage by application code.
 *
 */

/*! @brief SPI_PAL instance */
spi_instance_t spi3_palInstance =
{
    .instType = SPI_INST_TYPE_LPSPI,
    .instIdx = 2U
};

/* SPI Master Configurations */
spi_master_t spi3_MasterConfig0 =
{
    .baudRate      = 500000,
    .ssPolarity    = SPI_ACTIVE_HIGH,
    .frameSize     = 8,
    .clockPhase    = READ_ON_ODD_EDGE,
    .clockPolarity = SPI_ACTIVE_HIGH,
    .bitOrder      = SPI_TRANSFER_MSB_FIRST,
    .transferType  = SPI_USING_INTERRUPTS,
    .rxDMAChannel  = 255U,
    .txDMAChannel  = 255U,
    .callback      = NULL,
    .callbackParam = NULL,
    .ssPin         = 0,
    .extension     = NULL 
};
 
/* SPI Slave Configurations */
/* END spi3_pal. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

