/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : extWdog1.c
**     Project     : S32K1xxAppDev_Safety_Demo
**     Processor   : S32K144_100
**     Component   : ewm
**     Version     : Component SDK_S32K14x_12, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K14x_12
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-05-08, 00:45, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file extWdog1.c
** @version 01.00
*/
/*!
**  @addtogroup extWdog1_module extWdog1 module documentation
**  @{
*/

/* MODULE extWdog1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files by the user.
 */

#include "extWdog1.h"


/*! @brief extWdog1 configuration structures */


/*!
 * Configuration extWdog1_Config0
    -   1.984 ms counter period
    -   1.984 ms refresh window
 */
const ewm_init_config_t extWdog1_Config0 = {
    /* Module interrupt disabled */
    .interruptEnable    =   false,
    /* Prescaler */
    .prescaler          =   0U,
    /* Compare Low Value        */
    .compareLow         =   0U,
    /* Compare High Value       */
    .compareHigh        =   254U,
    /* Input pin logic          */
    .assertLogic        =   EWM_IN_ASSERT_DISABLED
};
/* END extWdog1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/



