/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Tue Sep 26 18:04:00 2017. */

#include "Telaidian.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EventUpload_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, EventUpload, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, EventUpload, stationId, key, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, EventUpload, timestamp, stationId, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, EventUpload, uuid, timestamp, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, EventUpload, bean, uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t StartChargeResultUp_fields[9] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StartChargeResultUp, canId, canId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, StartChargeResultUp, billId, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, StartChargeResultUp, chargeMode, billId, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, StartChargeResultUp, result, chargeMode, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, StartChargeResultUp, endReason, result, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, StartChargeResultUp, pileState, endReason, 0),
    PB_FIELD(  7, STRING  , SINGULAR, CALLBACK, OTHER, StartChargeResultUp, resFieldOne, pileState, 0),
    PB_FIELD(  8, STRING  , SINGULAR, CALLBACK, OTHER, StartChargeResultUp, resFieldTwo, resFieldOne, 0),
    PB_LAST_FIELD
};

const pb_field_t StopChargeResultUp_fields[7] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StopChargeResultUp, canId, canId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, StopChargeResultUp, billId, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, StopChargeResultUp, chargeMode, billId, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, StopChargeResultUp, result, chargeMode, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, StopChargeResultUp, endReason, result, 0),
    PB_FIELD(  6, STRING  , SINGULAR, CALLBACK, OTHER, StopChargeResultUp, freezeMeters, endReason, 0),
    PB_LAST_FIELD
};

const pb_field_t TelesignallingDataUp_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, TelesignallingDataUp, teleSigns, teleSigns, &TelesignallingDataUp_Telesignalling_fields),
    PB_LAST_FIELD
};

const pb_field_t TelesignallingDataUp_Telesignalling_fields[15] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TelesignallingDataUp_Telesignalling, canIndex, canIndex, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, linkStatus, canIndex, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, chargerStatus, linkStatus, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, relayState, chargerStatus, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, parkStatus, relayState, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, lockStatus, parkStatus, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, faultStatus, lockStatus, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, BMSFaultStatus, faultStatus, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, stopReason, BMSFaultStatus, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, strategy, stopReason, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, model, strategy, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, auxiliaryPower, model, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, chargeInterfaceStatus, auxiliaryPower, 0),
    PB_FIELD( 14, INT32   , SINGULAR, STATIC  , OTHER, TelesignallingDataUp_Telesignalling, burstData, chargeInterfaceStatus, 0),
    PB_LAST_FIELD
};

const pb_field_t TelemetryDataUp_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, TelemetryDataUp, telemetry, telemetry, &TelemetryDataUp_Telemetry_fields),
    PB_LAST_FIELD
};

const pb_field_t TelemetryDataUp_Telemetry_fields[16] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, TelemetryDataUp_Telemetry, canIndex, canIndex, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, aVoltage, canIndex, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, bVoltage, aVoltage, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, cVoltage, bVoltage, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, acurrent, cVoltage, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, bcurrent, acurrent, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, ccurrent, bcurrent, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, activePower, ccurrent, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, reactivePower, activePower, 0),
    PB_FIELD( 10, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, totalPowerFactor, reactivePower, 0),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, zeroLineCurrent, totalPowerFactor, 0),
    PB_FIELD( 12, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, voltageUR, zeroLineCurrent, 0),
    PB_FIELD( 13, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, currentUR, voltageUR, 0),
    PB_FIELD( 14, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, directVoltage, currentUR, 0),
    PB_FIELD( 15, INT32   , SINGULAR, STATIC  , OTHER, TelemetryDataUp_Telemetry, directCurrent, directVoltage, 0),
    PB_LAST_FIELD
};

const pb_field_t MeterDataUp_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, MeterDataUp, meter, meter, &MeterDataUp_Meter_fields),
    PB_LAST_FIELD
};

const pb_field_t MeterDataUp_Meter_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, MeterDataUp_Meter, canIndex, canIndex, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, MeterDataUp_Meter, positiveActiveEnergy, canIndex, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, MeterDataUp_Meter, positiveReactiveEnergy, positiveActiveEnergy, 0),
    PB_LAST_FIELD
};

const pb_field_t BMSDataUp_fields[9] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, BMSDataUp, canIndex, canIndex, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, BMSDataUp, soc, canIndex, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, BMSDataUp, demandVoltage, soc, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, BMSDataUp, demandCurrent, demandVoltage, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, BMSDataUp, highestTemp, demandCurrent, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, BMSDataUp, highestVoltage, highestTemp, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, BMSDataUp, lowestTemp, highestVoltage, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, BMSDataUp, lowestVoltage, lowestTemp, 0),
    PB_LAST_FIELD
};

const pb_field_t EventStateUpload_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, EventStateUpload, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, EventStateUpload, stationId, key, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, EventStateUpload, timestamp, stationId, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, EventStateUpload, uuid, timestamp, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, EventStateUpload, bean, uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t StateDataUp_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StateDataUp, type, type, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, StateDataUp, timestamp, type, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, StateDataUp, authen, timestamp, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, StateDataUp, resFieldOne, authen, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, StateDataUp, resFieldTwo, resFieldOne, 0),
    PB_LAST_FIELD
};

const pb_field_t EventStatePushdown_fields[5] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, EventStatePushdown, key, key, 0),
    PB_FIELD(  2, UINT64  , SINGULAR, STATIC  , OTHER, EventStatePushdown, timestamp, key, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, EventStatePushdown, uuid, timestamp, 0),
    PB_FIELD(  4, BYTES   , SINGULAR, CALLBACK, OTHER, EventStatePushdown, bean, uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t CallAllStatePush_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, CallAllStatePush, resFieldOne, resFieldOne, 0),
    PB_LAST_FIELD
};

const pb_field_t CallControllerStatePush_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, CallControllerStatePush, stationId, stationId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, CallControllerStatePush, resFieldOne, stationId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, CallControllerStatePush, resFieldTwo, resFieldOne, 0),
    PB_LAST_FIELD
};

const pb_field_t EventRequest_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, EventRequest, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, EventRequest, stationId, key, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, EventRequest, timestamp, stationId, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, EventRequest, uuid, timestamp, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, EventRequest, bean, uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t StartChargeRequest_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StartChargeRequest, startChargeMode, startChargeMode, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, StartChargeRequest, canId, startChargeMode, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, StartChargeRequest, accountId, canId, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, StartChargeRequest, chargeType, accountId, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, StartChargeRequest, value, chargeType, 0),
    PB_LAST_FIELD
};

const pb_field_t StopChargeRequest_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StopChargeRequest, stopChargeMode, stopChargeMode, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, StopChargeRequest, canId, stopChargeMode, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, StopChargeRequest, accountId, canId, 0),
    PB_LAST_FIELD
};

const pb_field_t AccountRequest_fields[4] = {
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , FIRST, AccountRequest, canId, canId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, AccountRequest, accountId, canId, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, AccountRequest, reqType, accountId, 0),
    PB_LAST_FIELD
};

const pb_field_t EventResponse_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, EventResponse, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, EventResponse, stationId, key, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, EventResponse, timestamp, stationId, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, EventResponse, uuid, timestamp, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, EventResponse, bean, uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t AccountResponse_fields[5] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, AccountResponse, canId, canId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, AccountResponse, accountId, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, AccountResponse, respType, accountId, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, AccountResponse, itemDetail, respType, 0),
    PB_LAST_FIELD
};

const pb_field_t ChargeAckResponse_fields[5] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ChargeAckResponse, canId, canId, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, ChargeAckResponse, chargeMode, canId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, ChargeAckResponse, accountId, chargeMode, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, ChargeAckResponse, result, accountId, 0),
    PB_LAST_FIELD
};

const pb_field_t EventPushdown_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, EventPushdown, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, EventPushdown, stationId, key, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, EventPushdown, timestamp, stationId, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, EventPushdown, uuid, timestamp, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, EventPushdown, bean, uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t StartChargeOrderPush_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StartChargeOrderPush, canId, canId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, StartChargeOrderPush, billId, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, StartChargeOrderPush, chargeMode, billId, 0),
    PB_LAST_FIELD
};

const pb_field_t StopChargeOrderPush_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StopChargeOrderPush, canId, canId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, StopChargeOrderPush, billId, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, StopChargeOrderPush, chargeMode, billId, 0),
    PB_LAST_FIELD
};

const pb_field_t CallAllDataPush_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, CallAllDataPush, telesData, telesData, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, CallAllDataPush, telemData, telesData, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, CallAllDataPush, meterData, telemData, 0),
    PB_LAST_FIELD
};

const pb_field_t CallPileDataPush_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, CallPileDataPush, canId, canId, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, telesData, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, telemData, telesData, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, meterData, telemData, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, bmsData, meterData, 0),
    PB_LAST_FIELD
};

const pb_field_t DataAckPush_fields[5] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, DataAckPush, canId, canId, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, DataAckPush, ackType, canId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, DataAckPush, accountId, ackType, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, DataAckPush, result, accountId, 0),
    PB_LAST_FIELD
};

const pb_field_t ClockSynPush_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ClockSynPush, times, times, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ClockSynPush, bcdTimeStamp, times, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
