/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue Sep 26 18:04:00 2017. */

#ifndef PB_TELAIDIAN_PB_H_INCLUDED
#define PB_TELAIDIAN_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _CallAllStatePush {
    pb_callback_t resFieldOne;
/* @@protoc_insertion_point(struct:CallAllStatePush) */
} CallAllStatePush;

typedef struct _CallControllerStatePush {
    pb_callback_t stationId;
    pb_callback_t resFieldOne;
    pb_callback_t resFieldTwo;
/* @@protoc_insertion_point(struct:CallControllerStatePush) */
} CallControllerStatePush;

typedef struct _MeterDataUp {
    pb_callback_t meter;
/* @@protoc_insertion_point(struct:MeterDataUp) */
} MeterDataUp;

typedef struct _TelemetryDataUp {
    pb_callback_t telemetry;
/* @@protoc_insertion_point(struct:TelemetryDataUp) */
} TelemetryDataUp;

typedef struct _TelesignallingDataUp {
    pb_callback_t teleSigns;
/* @@protoc_insertion_point(struct:TelesignallingDataUp) */
} TelesignallingDataUp;

typedef struct _AccountRequest {
    int32_t canId;
    pb_callback_t accountId;
    int32_t reqType;
/* @@protoc_insertion_point(struct:AccountRequest) */
} AccountRequest;

typedef struct _AccountResponse {
    int32_t canId;
    pb_callback_t accountId;
    int32_t respType;
    pb_callback_t itemDetail;
/* @@protoc_insertion_point(struct:AccountResponse) */
} AccountResponse;

typedef struct _BMSDataUp {
    int32_t canIndex;
    int32_t soc;
    int32_t demandVoltage;
    int32_t demandCurrent;
    int32_t highestTemp;
    int32_t highestVoltage;
    int32_t lowestTemp;
    int32_t lowestVoltage;
/* @@protoc_insertion_point(struct:BMSDataUp) */
} BMSDataUp;

typedef struct _CallAllDataPush {
    int32_t telesData;
    int32_t telemData;
    int32_t meterData;
/* @@protoc_insertion_point(struct:CallAllDataPush) */
} CallAllDataPush;

typedef struct _CallPileDataPush {
    int32_t canId;
    int32_t telesData;
    int32_t telemData;
    int32_t meterData;
    int32_t bmsData;
/* @@protoc_insertion_point(struct:CallPileDataPush) */
} CallPileDataPush;

typedef struct _ChargeAckResponse {
    int32_t canId;
    int32_t chargeMode;
    pb_callback_t accountId;
    int32_t result;
/* @@protoc_insertion_point(struct:ChargeAckResponse) */
} ChargeAckResponse;

typedef struct _ClockSynPush {
    int32_t times;
    pb_callback_t bcdTimeStamp;
/* @@protoc_insertion_point(struct:ClockSynPush) */
} ClockSynPush;

typedef struct _DataAckPush {
    int32_t canId;
    int32_t ackType;
    pb_callback_t accountId;
    int32_t result;
/* @@protoc_insertion_point(struct:DataAckPush) */
} DataAckPush;

typedef struct _EventPushdown {
    int32_t key;
    pb_callback_t stationId;
    uint64_t timestamp;
    pb_callback_t uuid;
    pb_callback_t bean;
/* @@protoc_insertion_point(struct:EventPushdown) */
} EventPushdown;

typedef struct _EventRequest {
    int32_t key;
    pb_callback_t stationId;
    uint64_t timestamp;
    pb_callback_t uuid;
    pb_callback_t bean;
/* @@protoc_insertion_point(struct:EventRequest) */
} EventRequest;

typedef struct _EventResponse {
    int32_t key;
    pb_callback_t stationId;
    uint64_t timestamp;
    pb_callback_t uuid;
    pb_callback_t bean;
/* @@protoc_insertion_point(struct:EventResponse) */
} EventResponse;

typedef struct _EventStatePushdown {
    int32_t key;
    uint64_t timestamp;
    pb_callback_t uuid;
    pb_callback_t bean;
/* @@protoc_insertion_point(struct:EventStatePushdown) */
} EventStatePushdown;

typedef struct _EventStateUpload {
    int32_t key;
    pb_callback_t stationId;
    uint64_t timestamp;
    pb_callback_t uuid;
    pb_callback_t bean;
/* @@protoc_insertion_point(struct:EventStateUpload) */
} EventStateUpload;

typedef struct _EventUpload {
    int32_t key;
    pb_callback_t stationId;
    uint64_t timestamp;
    pb_callback_t uuid;
    pb_callback_t bean;
/* @@protoc_insertion_point(struct:EventUpload) */
} EventUpload;

typedef struct _MeterDataUp_Meter {
    int32_t canIndex;
    int32_t positiveActiveEnergy;
    int32_t positiveReactiveEnergy;
/* @@protoc_insertion_point(struct:MeterDataUp_Meter) */
} MeterDataUp_Meter;

typedef struct _StartChargeOrderPush {
    int32_t canId;
    pb_callback_t billId;
    int32_t chargeMode;
/* @@protoc_insertion_point(struct:StartChargeOrderPush) */
} StartChargeOrderPush;

typedef struct _StartChargeRequest {
    int32_t startChargeMode;
    int32_t canId;
    pb_callback_t accountId;
    int32_t chargeType;
    int32_t value;
/* @@protoc_insertion_point(struct:StartChargeRequest) */
} StartChargeRequest;

typedef struct _StartChargeResultUp {
    int32_t canId;
    pb_callback_t billId;
    int32_t chargeMode;
    int32_t result;
    int32_t endReason;
    int32_t pileState;
    pb_callback_t resFieldOne;
    pb_callback_t resFieldTwo;
/* @@protoc_insertion_point(struct:StartChargeResultUp) */
} StartChargeResultUp;

typedef struct _StateDataUp {
    int32_t type;
    uint64_t timestamp;
    pb_callback_t authen;
    pb_callback_t resFieldOne;
    pb_callback_t resFieldTwo;
/* @@protoc_insertion_point(struct:StateDataUp) */
} StateDataUp;

typedef struct _StopChargeOrderPush {
    int32_t canId;
    pb_callback_t billId;
    int32_t chargeMode;
/* @@protoc_insertion_point(struct:StopChargeOrderPush) */
} StopChargeOrderPush;

typedef struct _StopChargeRequest {
    int32_t stopChargeMode;
    int32_t canId;
    pb_callback_t accountId;
/* @@protoc_insertion_point(struct:StopChargeRequest) */
} StopChargeRequest;

typedef struct _StopChargeResultUp {
    int32_t canId;
    pb_callback_t billId;
    int32_t chargeMode;
    int32_t result;
    int32_t endReason;
    pb_callback_t freezeMeters;
/* @@protoc_insertion_point(struct:StopChargeResultUp) */
} StopChargeResultUp;

typedef struct _TelemetryDataUp_Telemetry {
    int32_t canIndex;
    int32_t aVoltage;
    int32_t bVoltage;
    int32_t cVoltage;
    int32_t acurrent;
    int32_t bcurrent;
    int32_t ccurrent;
    int32_t activePower;
    int32_t reactivePower;
    int32_t totalPowerFactor;
    int32_t zeroLineCurrent;
    int32_t voltageUR;
    int32_t currentUR;
    int32_t directVoltage;
    int32_t directCurrent;
/* @@protoc_insertion_point(struct:TelemetryDataUp_Telemetry) */
} TelemetryDataUp_Telemetry;

typedef struct _TelesignallingDataUp_Telesignalling {
    int32_t canIndex;
    int32_t linkStatus;
    int32_t chargerStatus;
    int32_t relayState;
    int32_t parkStatus;
    int32_t lockStatus;
    int32_t faultStatus;
    int32_t BMSFaultStatus;
    int32_t stopReason;
    int32_t strategy;
    int32_t model;
    int32_t auxiliaryPower;
    int32_t chargeInterfaceStatus;
    int32_t burstData;
/* @@protoc_insertion_point(struct:TelesignallingDataUp_Telesignalling) */
} TelesignallingDataUp_Telesignalling;

/* Default values for struct fields */

/* Initializer values for message structs */
#define EventUpload_init_default                 {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeResultUp_init_default         {0, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StopChargeResultUp_init_default          {0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define TelesignallingDataUp_init_default        {{{NULL}, NULL}}
#define TelesignallingDataUp_Telesignalling_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TelemetryDataUp_init_default             {{{NULL}, NULL}}
#define TelemetryDataUp_Telemetry_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MeterDataUp_init_default                 {{{NULL}, NULL}}
#define MeterDataUp_Meter_init_default           {0, 0, 0}
#define BMSDataUp_init_default                   {0, 0, 0, 0, 0, 0, 0, 0}
#define EventStateUpload_init_default            {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StateDataUp_init_default                 {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define EventStatePushdown_init_default          {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define CallAllStatePush_init_default            {{{NULL}, NULL}}
#define CallControllerStatePush_init_default     {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define EventRequest_init_default                {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeRequest_init_default          {0, 0, {{NULL}, NULL}, 0, 0}
#define StopChargeRequest_init_default           {0, 0, {{NULL}, NULL}}
#define AccountRequest_init_default              {0, {{NULL}, NULL}, 0}
#define EventResponse_init_default               {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AccountResponse_init_default             {0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ChargeAckResponse_init_default           {0, 0, {{NULL}, NULL}, 0}
#define EventPushdown_init_default               {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeOrderPush_init_default        {0, {{NULL}, NULL}, 0}
#define StopChargeOrderPush_init_default         {0, {{NULL}, NULL}, 0}
#define CallAllDataPush_init_default             {0, 0, 0}
#define CallPileDataPush_init_default            {0, 0, 0, 0, 0}
#define DataAckPush_init_default                 {0, 0, {{NULL}, NULL}, 0}
#define ClockSynPush_init_default                {0, {{NULL}, NULL}}
#define EventUpload_init_zero                    {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeResultUp_init_zero            {0, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StopChargeResultUp_init_zero             {0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define TelesignallingDataUp_init_zero           {{{NULL}, NULL}}
#define TelesignallingDataUp_Telesignalling_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define TelemetryDataUp_init_zero                {{{NULL}, NULL}}
#define TelemetryDataUp_Telemetry_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MeterDataUp_init_zero                    {{{NULL}, NULL}}
#define MeterDataUp_Meter_init_zero              {0, 0, 0}
#define BMSDataUp_init_zero                      {0, 0, 0, 0, 0, 0, 0, 0}
#define EventStateUpload_init_zero               {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StateDataUp_init_zero                    {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define EventStatePushdown_init_zero             {0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define CallAllStatePush_init_zero               {{{NULL}, NULL}}
#define CallControllerStatePush_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define EventRequest_init_zero                   {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeRequest_init_zero             {0, 0, {{NULL}, NULL}, 0, 0}
#define StopChargeRequest_init_zero              {0, 0, {{NULL}, NULL}}
#define AccountRequest_init_zero                 {0, {{NULL}, NULL}, 0}
#define EventResponse_init_zero                  {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define AccountResponse_init_zero                {0, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define ChargeAckResponse_init_zero              {0, 0, {{NULL}, NULL}, 0}
#define EventPushdown_init_zero                  {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeOrderPush_init_zero           {0, {{NULL}, NULL}, 0}
#define StopChargeOrderPush_init_zero            {0, {{NULL}, NULL}, 0}
#define CallAllDataPush_init_zero                {0, 0, 0}
#define CallPileDataPush_init_zero               {0, 0, 0, 0, 0}
#define DataAckPush_init_zero                    {0, 0, {{NULL}, NULL}, 0}
#define ClockSynPush_init_zero                   {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define CallAllStatePush_resFieldOne_tag         1
#define CallControllerStatePush_stationId_tag    1
#define CallControllerStatePush_resFieldOne_tag  2
#define CallControllerStatePush_resFieldTwo_tag  3
#define MeterDataUp_meter_tag                    1
#define TelemetryDataUp_telemetry_tag            1
#define TelesignallingDataUp_teleSigns_tag       1
#define AccountRequest_canId_tag                 2
#define AccountRequest_accountId_tag             3
#define AccountRequest_reqType_tag               4
#define AccountResponse_canId_tag                1
#define AccountResponse_accountId_tag            2
#define AccountResponse_respType_tag             3
#define AccountResponse_itemDetail_tag           4
#define BMSDataUp_canIndex_tag                   1
#define BMSDataUp_soc_tag                        2
#define BMSDataUp_demandVoltage_tag              3
#define BMSDataUp_demandCurrent_tag              4
#define BMSDataUp_highestTemp_tag                5
#define BMSDataUp_highestVoltage_tag             6
#define BMSDataUp_lowestTemp_tag                 7
#define BMSDataUp_lowestVoltage_tag              8
#define CallAllDataPush_telesData_tag            1
#define CallAllDataPush_telemData_tag            2
#define CallAllDataPush_meterData_tag            3
#define CallPileDataPush_canId_tag               1
#define CallPileDataPush_telesData_tag           2
#define CallPileDataPush_telemData_tag           3
#define CallPileDataPush_meterData_tag           4
#define CallPileDataPush_bmsData_tag             5
#define ChargeAckResponse_canId_tag              1
#define ChargeAckResponse_chargeMode_tag         2
#define ChargeAckResponse_accountId_tag          3
#define ChargeAckResponse_result_tag             4
#define ClockSynPush_times_tag                   1
#define ClockSynPush_bcdTimeStamp_tag            2
#define DataAckPush_canId_tag                    1
#define DataAckPush_ackType_tag                  2
#define DataAckPush_accountId_tag                3
#define DataAckPush_result_tag                   4
#define EventPushdown_key_tag                    1
#define EventPushdown_stationId_tag              2
#define EventPushdown_timestamp_tag              3
#define EventPushdown_uuid_tag                   4
#define EventPushdown_bean_tag                   5
#define EventRequest_key_tag                     1
#define EventRequest_stationId_tag               2
#define EventRequest_timestamp_tag               3
#define EventRequest_uuid_tag                    4
#define EventRequest_bean_tag                    5
#define EventResponse_key_tag                    1
#define EventResponse_stationId_tag              2
#define EventResponse_timestamp_tag              3
#define EventResponse_uuid_tag                   4
#define EventResponse_bean_tag                   5
#define EventStatePushdown_key_tag               1
#define EventStatePushdown_timestamp_tag         2
#define EventStatePushdown_uuid_tag              3
#define EventStatePushdown_bean_tag              4
#define EventStateUpload_key_tag                 1
#define EventStateUpload_stationId_tag           2
#define EventStateUpload_timestamp_tag           3
#define EventStateUpload_uuid_tag                4
#define EventStateUpload_bean_tag                5
#define EventUpload_key_tag                      1
#define EventUpload_stationId_tag                2
#define EventUpload_timestamp_tag                3
#define EventUpload_uuid_tag                     4
#define EventUpload_bean_tag                     5
#define MeterDataUp_Meter_canIndex_tag           1
#define MeterDataUp_Meter_positiveActiveEnergy_tag 2
#define MeterDataUp_Meter_positiveReactiveEnergy_tag 3
#define StartChargeOrderPush_canId_tag           1
#define StartChargeOrderPush_billId_tag          2
#define StartChargeOrderPush_chargeMode_tag      3
#define StartChargeRequest_startChargeMode_tag   1
#define StartChargeRequest_canId_tag             2
#define StartChargeRequest_accountId_tag         3
#define StartChargeRequest_chargeType_tag        4
#define StartChargeRequest_value_tag             5
#define StartChargeResultUp_canId_tag            1
#define StartChargeResultUp_billId_tag           2
#define StartChargeResultUp_chargeMode_tag       3
#define StartChargeResultUp_result_tag           4
#define StartChargeResultUp_endReason_tag        5
#define StartChargeResultUp_pileState_tag        6
#define StartChargeResultUp_resFieldOne_tag      7
#define StartChargeResultUp_resFieldTwo_tag      8
#define StateDataUp_type_tag                     1
#define StateDataUp_timestamp_tag                2
#define StateDataUp_authen_tag                   3
#define StateDataUp_resFieldOne_tag              4
#define StateDataUp_resFieldTwo_tag              5
#define StopChargeOrderPush_canId_tag            1
#define StopChargeOrderPush_billId_tag           2
#define StopChargeOrderPush_chargeMode_tag       3
#define StopChargeRequest_stopChargeMode_tag     1
#define StopChargeRequest_canId_tag              2
#define StopChargeRequest_accountId_tag          3
#define StopChargeResultUp_canId_tag             1
#define StopChargeResultUp_billId_tag            2
#define StopChargeResultUp_chargeMode_tag        3
#define StopChargeResultUp_result_tag            4
#define StopChargeResultUp_endReason_tag         5
#define StopChargeResultUp_freezeMeters_tag      6
#define TelemetryDataUp_Telemetry_canIndex_tag   1
#define TelemetryDataUp_Telemetry_aVoltage_tag   2
#define TelemetryDataUp_Telemetry_bVoltage_tag   3
#define TelemetryDataUp_Telemetry_cVoltage_tag   4
#define TelemetryDataUp_Telemetry_acurrent_tag   5
#define TelemetryDataUp_Telemetry_bcurrent_tag   6
#define TelemetryDataUp_Telemetry_ccurrent_tag   7
#define TelemetryDataUp_Telemetry_activePower_tag 8
#define TelemetryDataUp_Telemetry_reactivePower_tag 9
#define TelemetryDataUp_Telemetry_totalPowerFactor_tag 10
#define TelemetryDataUp_Telemetry_zeroLineCurrent_tag 11
#define TelemetryDataUp_Telemetry_voltageUR_tag  12
#define TelemetryDataUp_Telemetry_currentUR_tag  13
#define TelemetryDataUp_Telemetry_directVoltage_tag 14
#define TelemetryDataUp_Telemetry_directCurrent_tag 15
#define TelesignallingDataUp_Telesignalling_canIndex_tag 1
#define TelesignallingDataUp_Telesignalling_linkStatus_tag 2
#define TelesignallingDataUp_Telesignalling_chargerStatus_tag 3
#define TelesignallingDataUp_Telesignalling_relayState_tag 4
#define TelesignallingDataUp_Telesignalling_parkStatus_tag 5
#define TelesignallingDataUp_Telesignalling_lockStatus_tag 6
#define TelesignallingDataUp_Telesignalling_faultStatus_tag 7
#define TelesignallingDataUp_Telesignalling_BMSFaultStatus_tag 8
#define TelesignallingDataUp_Telesignalling_stopReason_tag 9
#define TelesignallingDataUp_Telesignalling_strategy_tag 10
#define TelesignallingDataUp_Telesignalling_model_tag 11
#define TelesignallingDataUp_Telesignalling_auxiliaryPower_tag 12
#define TelesignallingDataUp_Telesignalling_chargeInterfaceStatus_tag 13
#define TelesignallingDataUp_Telesignalling_burstData_tag 14

/* Struct field encoding specification for nanopb */
extern const pb_field_t EventUpload_fields[6];
extern const pb_field_t StartChargeResultUp_fields[9];
extern const pb_field_t StopChargeResultUp_fields[7];
extern const pb_field_t TelesignallingDataUp_fields[2];
extern const pb_field_t TelesignallingDataUp_Telesignalling_fields[15];
extern const pb_field_t TelemetryDataUp_fields[2];
extern const pb_field_t TelemetryDataUp_Telemetry_fields[16];
extern const pb_field_t MeterDataUp_fields[2];
extern const pb_field_t MeterDataUp_Meter_fields[4];
extern const pb_field_t BMSDataUp_fields[9];
extern const pb_field_t EventStateUpload_fields[6];
extern const pb_field_t StateDataUp_fields[6];
extern const pb_field_t EventStatePushdown_fields[5];
extern const pb_field_t CallAllStatePush_fields[2];
extern const pb_field_t CallControllerStatePush_fields[4];
extern const pb_field_t EventRequest_fields[6];
extern const pb_field_t StartChargeRequest_fields[6];
extern const pb_field_t StopChargeRequest_fields[4];
extern const pb_field_t AccountRequest_fields[4];
extern const pb_field_t EventResponse_fields[6];
extern const pb_field_t AccountResponse_fields[5];
extern const pb_field_t ChargeAckResponse_fields[5];
extern const pb_field_t EventPushdown_fields[6];
extern const pb_field_t StartChargeOrderPush_fields[4];
extern const pb_field_t StopChargeOrderPush_fields[4];
extern const pb_field_t CallAllDataPush_fields[4];
extern const pb_field_t CallPileDataPush_fields[6];
extern const pb_field_t DataAckPush_fields[5];
extern const pb_field_t ClockSynPush_fields[3];

/* Maximum encoded size of messages (where known) */
/* EventUpload_size depends on runtime parameters */
/* StartChargeResultUp_size depends on runtime parameters */
/* StopChargeResultUp_size depends on runtime parameters */
/* TelesignallingDataUp_size depends on runtime parameters */
#define TelesignallingDataUp_Telesignalling_size 154
/* TelemetryDataUp_size depends on runtime parameters */
#define TelemetryDataUp_Telemetry_size           165
/* MeterDataUp_size depends on runtime parameters */
#define MeterDataUp_Meter_size                   33
#define BMSDataUp_size                           88
/* EventStateUpload_size depends on runtime parameters */
/* StateDataUp_size depends on runtime parameters */
/* EventStatePushdown_size depends on runtime parameters */
/* CallAllStatePush_size depends on runtime parameters */
/* CallControllerStatePush_size depends on runtime parameters */
/* EventRequest_size depends on runtime parameters */
/* StartChargeRequest_size depends on runtime parameters */
/* StopChargeRequest_size depends on runtime parameters */
/* AccountRequest_size depends on runtime parameters */
/* EventResponse_size depends on runtime parameters */
/* AccountResponse_size depends on runtime parameters */
/* ChargeAckResponse_size depends on runtime parameters */
/* EventPushdown_size depends on runtime parameters */
/* StartChargeOrderPush_size depends on runtime parameters */
/* StopChargeOrderPush_size depends on runtime parameters */
#define CallAllDataPush_size                     33
#define CallPileDataPush_size                    55
/* DataAckPush_size depends on runtime parameters */
/* ClockSynPush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TELAIDIAN_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
