/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Fri Sep 22 15:04:32 2017. */

#ifndef PB_TELD_PB_H_INCLUDED
#define PB_TELD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _CallAllDataPush {
    int32_t telesData;
    int32_t telemData;
    int32_t meterData;
/* @@protoc_insertion_point(struct:CallAllDataPush) */
} CallAllDataPush;

typedef struct _CallPileDataPush {
    int32_t canId;
    int32_t telesData;
    int32_t telemData;
    int32_t meterData;
    int32_t bmsData;
/* @@protoc_insertion_point(struct:CallPileDataPush) */
} CallPileDataPush;

typedef struct _ClockSynPush {
    int32_t times;
    pb_callback_t bcdTimeStamp;
/* @@protoc_insertion_point(struct:ClockSynPush) */
} ClockSynPush;

typedef struct _DataAckPush {
    int32_t canId;
    int32_t ackType;
    pb_callback_t accountId;
    int32_t result;
/* @@protoc_insertion_point(struct:DataAckPush) */
} DataAckPush;

typedef struct _EventPushdown {
    int32_t key;
    pb_callback_t stationId;
    uint64_t timestamp;
    pb_callback_t uuid;
    pb_callback_t bean;
/* @@protoc_insertion_point(struct:EventPushdown) */
} EventPushdown;

typedef struct _StartChargeOrderPush {
    int32_t canId;
    pb_callback_t billId;
    int32_t chargeMode;
/* @@protoc_insertion_point(struct:StartChargeOrderPush) */
} StartChargeOrderPush;

typedef struct _StopChargeOrderPush {
    int32_t canId;
    pb_callback_t billId;
    int32_t chargeMode;
/* @@protoc_insertion_point(struct:StopChargeOrderPush) */
} StopChargeOrderPush;

/* Default values for struct fields */

/* Initializer values for message structs */
#define EventPushdown_init_default               {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeOrderPush_init_default        {0, {{NULL}, NULL}, 0}
#define StopChargeOrderPush_init_default         {0, {{NULL}, NULL}, 0}
#define CallAllDataPush_init_default             {0, 0, 0}
#define CallPileDataPush_init_default            {0, 0, 0, 0, 0}
#define DataAckPush_init_default                 {0, 0, {{NULL}, NULL}, 0}
#define ClockSynPush_init_default                {0, {{NULL}, NULL}}
#define EventPushdown_init_zero                  {0, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define StartChargeOrderPush_init_zero           {0, {{NULL}, NULL}, 0}
#define StopChargeOrderPush_init_zero            {0, {{NULL}, NULL}, 0}
#define CallAllDataPush_init_zero                {0, 0, 0}
#define CallPileDataPush_init_zero               {0, 0, 0, 0, 0}
#define DataAckPush_init_zero                    {0, 0, {{NULL}, NULL}, 0}
#define ClockSynPush_init_zero                   {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define CallAllDataPush_telesData_tag            1
#define CallAllDataPush_telemData_tag            2
#define CallAllDataPush_meterData_tag            3
#define CallPileDataPush_canId_tag               1
#define CallPileDataPush_telesData_tag           2
#define CallPileDataPush_telemData_tag           3
#define CallPileDataPush_meterData_tag           4
#define CallPileDataPush_bmsData_tag             5
#define ClockSynPush_times_tag                   1
#define ClockSynPush_bcdTimeStamp_tag            2
#define DataAckPush_canId_tag                    1
#define DataAckPush_ackType_tag                  2
#define DataAckPush_accountId_tag                3
#define DataAckPush_result_tag                   4
#define EventPushdown_key_tag                    1
#define EventPushdown_stationId_tag              2
#define EventPushdown_timestamp_tag              3
#define EventPushdown_uuid_tag                   4
#define EventPushdown_bean_tag                   5
#define StartChargeOrderPush_canId_tag           1
#define StartChargeOrderPush_billId_tag          2
#define StartChargeOrderPush_chargeMode_tag      3
#define StopChargeOrderPush_canId_tag            1
#define StopChargeOrderPush_billId_tag           2
#define StopChargeOrderPush_chargeMode_tag       3

/* Struct field encoding specification for nanopb */
extern const pb_field_t EventPushdown_fields[6];
extern const pb_field_t StartChargeOrderPush_fields[4];
extern const pb_field_t StopChargeOrderPush_fields[4];
extern const pb_field_t CallAllDataPush_fields[4];
extern const pb_field_t CallPileDataPush_fields[6];
extern const pb_field_t DataAckPush_fields[5];
extern const pb_field_t ClockSynPush_fields[3];

/* Maximum encoded size of messages (where known) */
/* EventPushdown_size depends on runtime parameters */
/* StartChargeOrderPush_size depends on runtime parameters */
/* StopChargeOrderPush_size depends on runtime parameters */
#define CallAllDataPush_size                     33
#define CallPileDataPush_size                    55
/* DataAckPush_size depends on runtime parameters */
/* ClockSynPush_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TELD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
