/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Sep 22 15:04:32 2017. */

#include "Teld.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EventPushdown_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, EventPushdown, key, key, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, EventPushdown, stationId, key, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, EventPushdown, timestamp, stationId, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, EventPushdown, uuid, timestamp, 0),
    PB_FIELD(  5, BYTES   , SINGULAR, CALLBACK, OTHER, EventPushdown, bean, uuid, 0),
    PB_LAST_FIELD
};

const pb_field_t StartChargeOrderPush_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StartChargeOrderPush, canId, canId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, StartChargeOrderPush, billId, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, StartChargeOrderPush, chargeMode, billId, 0),
    PB_LAST_FIELD
};

const pb_field_t StopChargeOrderPush_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, StopChargeOrderPush, canId, canId, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, StopChargeOrderPush, billId, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, StopChargeOrderPush, chargeMode, billId, 0),
    PB_LAST_FIELD
};

const pb_field_t CallAllDataPush_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, CallAllDataPush, telesData, telesData, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, CallAllDataPush, telemData, telesData, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, CallAllDataPush, meterData, telemData, 0),
    PB_LAST_FIELD
};

const pb_field_t CallPileDataPush_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, CallPileDataPush, canId, canId, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, telesData, canId, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, telemData, telesData, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, meterData, telemData, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, CallPileDataPush, bmsData, meterData, 0),
    PB_LAST_FIELD
};

const pb_field_t DataAckPush_fields[5] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, DataAckPush, canId, canId, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, DataAckPush, ackType, canId, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, DataAckPush, accountId, ackType, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, DataAckPush, result, accountId, 0),
    PB_LAST_FIELD
};

const pb_field_t ClockSynPush_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ClockSynPush, times, times, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ClockSynPush, bcdTimeStamp, times, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
