################################################################################
# Automatically-generated file. Do not edit!
################################################################################

TODISASSEMBLE_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
O_SRCS_QUOTED := 
LD_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
O_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS_QUOTED := 
TOPREPROCESS_SRCS_OS_FORMAT := 
O_SRCS := 
ELF_SRCS := 
TOPREPROCESS_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C_SRCS_QUOTED := 
S_SRCS_QUOTED := 
ELF_SRCS_QUOTED := 
ELF_SRCS_OS_FORMAT := 
ASM_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
ASM_SRCS := 
S_UPPER_SRCS_OS_FORMAT := 
S_UPPER_SRCS := 
ASM_SRCS_QUOTED := 
OBJ_SRCS_QUOTED := 
LD_SRCS := 
LD_SRCS_QUOTED := 
OBJ_SRCS := 
S_SRCS := 
TOPREPROCESS_SRCS := 
C_SRCS := 
ASM_UPPER_SRCS_OS_FORMAT := 
SECONDARY_FLASH_QUOTED := 
SECONDARY_SIZE_OS_FORMAT := 
C_DEPS_QUOTED := 
SECONDARY_SIZE := 
OBJS_QUOTED := 
C_DEPS := 
C_DEPS_OS_FORMAT := 
OBJS_OS_FORMAT := 
EXECUTABLES_OS_FORMAT := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_FLASH_OS_FORMAT := 
SECONDARY_SIZE_QUOTED := 
EXECUTABLES_QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Generated_Code \
Project_Settings/Startup_Code \
SDK/platform/devices/S32K146/startup \
SDK/platform/devices \
SDK/platform/drivers/src/adc \
SDK/platform/drivers/src/clock/S32K1xx \
SDK/platform/drivers/src/crc \
SDK/platform/drivers/src/edma \
SDK/platform/drivers/src/erm \
SDK/platform/drivers/src/flash \
SDK/platform/drivers/src/flexcan \
SDK/platform/drivers/src/flexio \
SDK/platform/drivers/src/ftm \
SDK/platform/drivers/src/interrupt \
SDK/platform/drivers/src/lpi2c \
SDK/platform/drivers/src/lpit \
SDK/platform/drivers/src/lpspi \
SDK/platform/drivers/src/lptmr \
SDK/platform/drivers/src/lpuart \
SDK/platform/drivers/src/pdb \
SDK/platform/drivers/src/pins \
SDK/platform/drivers/src/rtc \
SDK/platform/drivers/src/trgmux \
SDK/platform/drivers/src/wdog \
SDK/platform/pal/src/adc \
SDK/platform/pal/src/can \
SDK/platform/pal/src/i2c \
SDK/platform/pal/src/pwm \
SDK/platform/pal/src/spi \
SDK/platform/pal/src/uart \
SDK/platform/pal/src/wdg \
SDK/rtos/FreeRTOS_S32K/Source \
SDK/rtos/FreeRTOS_S32K/Source/portable/GCC/ARM_CM4F \
SDK/rtos/FreeRTOS_S32K/Source/portable/MemMang \
SDK/rtos/osif \
Sources/Addition/Calibration \
Sources/Addition/LoadApp \
Sources/Addition/OperAuth \
Sources/Addition/UserDef \
Sources/Addition/UserProto \
Sources/BSPSys/BSPCfg \
Sources/BSPSys/BSPUser \
Sources/BSPSys/Device \
Sources/BSPSys/Device/FS65_driver \
Sources/BSPSys/Device/LTC2949_driver \
Sources/BSPSys/Device/LTC6813_driver \
Sources/BSPSys/Device/M24512_driver \
Sources/BSPSys/Device/MCP3913_driver \
Sources/BSPSys/Device/RX8010_driver \
Sources/BSPSys/Device/SST26VF064_driver \
Sources/BSPSys/Driver \
Sources/BSPSys/Util \
Sources/Funtion/CanLib \
Sources/Funtion/ChgCan \
Sources/Funtion/DataCalc \
Sources/Funtion/Diagnosis \
Sources/Funtion/EnergyCalc \
Sources/Funtion/Measurement \
Sources/Funtion/ModbusLib \
Sources/Funtion/Parameter \
Sources/Funtion/PowerManag \
Sources/Funtion/Recording \
Sources/Funtion/SocLib \
Sources/Funtion/Statistics \
Sources/Funtion/SystemInfo \
Sources/Logics/Balance \
Sources/Logics/CanUser \
Sources/Logics/EventUser \
Sources/Logics/FstChg \
Sources/Logics/SciUser \
Sources/Logics/Tactics \
Sources/OSUser \
Sources/SaftyCheck \
Sources/SaftyCheck/SafetyLib \
Sources \

