/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : ic_pal1.c
**     Project     : BMU_DEBUG_146
**     Processor   : S32K146_100
**     Component   : ic_pal
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-01-06, 13:58, # CodeGen: 1
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file ic_pal1.c
** @version 01.00
*/         
/*!
**  @addtogroup ic_pal1_module ic_pal1 module documentation
**  @{
*/         

/* Module ic_pal1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Required Rule 8.4, external symbol defined without a prior
 * declaration.
 * The symbols are declared in the driver header as external; the header is not included 
 * by this file.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source files in application code.
 */

#include "ic_pal1.h"


/*! @brief PAL instance information */
const ic_instance_t ic_pal1_instance = { IC_INST_TYPE_FTM, 2U };

/*! @brief Channel configuration array */
ic_input_ch_param_t ic_pal1_ChnConfig[1] =
{
    /* Channel configuration 0 */
    {
         .hwChannelId           = 0U,
         .inputCaptureMode      = IC_MEASURE_RISING_EDGE_PERIOD,
         .filterEn              = false,
         .filterValue           = 0U,
         .channelExtension      = &ic_pal1_ftmChnExtension0,
         .channelCallbackParams = NULL,
         .channelCallbacks      = PwmInputCapture_Callback
    }
};

channel_extension_ftm_for_ic_t ic_pal1_ftmChnExtension0 =
{
    /* Continuous measurement state 0 */
    .continuousModeEn = true
};


/*! @brief IP specific extension configuration */
extension_ftm_for_ic_t ic_pal1_ftmExtension =
{
    .ftmClockSource       = FTM_CLOCK_SOURCE_SYSTEMCLK,
    .ftmPrescaler         = FTM_CLOCK_DIVID_BY_128
};




/*! @brief Input capture configuration */
ic_config_t ic_pal1_InitConfig =
{
    .nNumChannels  = 1U,
    .inputChConfig = ic_pal1_ChnConfig,
    .extension     = &ic_pal1_ftmExtension
};


/* END ic_pal1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
