/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : timing_pal4.c
**     Project     : BMU_DEBUG_146
**     Processor   : S32K146_100
**     Component   : timing_pal
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-01-06, 13:58, # CodeGen: 1
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file timing_pal4.c
** @version 01.00
*/         
/*!
**  @addtogroup timing_pal4_module timing_pal4 module documentation
**  @{
*/         

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files, with the same initialized values.
 */

#include <stddef.h>
#include "timing_pal4.h"

/*! @brief PAL instance information */
const timing_instance_t timing_pal4_instance = { TIMING_INST_TYPE_LPTMR, 0U };

/*! @brief Channel configuration array */
timer_chan_config_t timing_pal4_channelConfigs[1] =
{
    /* Channel configuration 0 */
    {
         .channel        = 0U,
         .chanType       = TIMER_CHAN_TYPE_CONTINUOUS,
         .callback       = timing_pal1_LPTMR0_callBack0,
         .callbackParam  = NULL
    }
};
/*! @brief IP specific extension configuration */
extension_lptmr_for_timer_t timing_pal4_lptmrExtension =
{
    .clockSelect       = LPTMR_CLOCKSOURCE_1KHZ_LPO,
    .prescaler         = LPTMR_PRESCALE_2,
    .bypassPrescaler = true
};
/*! @brief Timer configuration */
timer_config_t timing_pal4_InitConfig =
{
    .chanConfigArray     = timing_pal4_channelConfigs,
    .numChan             = 1U,
    .extension           = &timing_pal4_lptmrExtension
};

/* END timing_pal4. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
